# Generated by Django 2.0.6 on 2018-07-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180702_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echo',
            old_name='user',
            new_name='owner',
        ),
    ]
