# Generated by Django 2.0.6 on 2018-07-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180702_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echo',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='echo',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
