# Generated by Django 2.0.6 on 2018-07-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180701_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
