# Generated by Django 2.0.6 on 2018-07-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180702_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echo',
            name='hearts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
