# Generated by Django 2.0.6 on 2018-07-04 23:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180704_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='echo',
            name='longitude',
        ),
        migrations.AddField(
            model_name='echo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
