# Generated by Django 2.0.6 on 2018-07-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180709_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echo',
            name='hearts',
        ),
        migrations.AddField(
            model_name='profile',
            name='hearts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
