# Generated by Django 2.0.6 on 2018-07-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_notification_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='echo',
            name='always_active',
            field=models.BooleanField(default=False),
        ),
    ]
